export const SIDEBAR_DATA = {
  "2026 VIDEO POOL EDITS": [
    "April 2026 Edits", "March 2026 Edits", "February 2026 Edits", "January 2026 Edits"
  ],
  "2025 VIDEO POOL EDITS": [
    "Jan 2025 Edits", "Feb 2025 Edits", "March 2025 Edits", "April Edits", "May 2025 Edits",
    "June 2025 Edits", "July 2025 Edits", "August 2025 Edits", "September 2025 Edits",
    "October 2025 Edits", "November 2025 Edits", "December 2025 Edits"
  ],
  "2024 VIDEO POOL EDITS": [
    "Jan 2024 Edits", "Feb 2024 Edits", "March 2024 Edits", "April Edits", "May 2024 Edits",
    "June 2024 Edits", "July 2024 Edits", "August 2024 Edits", "September 2024 Edits",
    "October 2024 Edits", "November 2024 Edits", "December 2024 Edits"
  ],
  "2023 VIDEO POOL EDITS": [
    "Jan 2023 Edits", "Feb 2023 Edits", "March 2023 Edits", "April 2023 Edits", "May 2023 Edits",
    "June 2023 Edits", "July 2023 Edits", "August 2023 Edits", "September 2023 Edits",
    "October 2023 Edits", "November 2023 Edits", "December 2023 Edits"
  ],
  "2022 VIDEO POOL EDITS": [
    "Jan 2022 Edits", "Feb 2022 Edits", "March 2022 Edits", "April 2022 Edits", "May 2022 Edits",
    "June 2022 Edits", "July 2022 Edits", "August 2022 Edits", "September 2022 Edits",
    "October 2022 Edits", "November 2022 Edits", "December 2022 Edits"
  ],
  "2021 VIDEO POOL EDITS": [
    "JANUARY 2021 EDITS", "FEB 2021 EDITS", "March 2021 Edits", "April 2021 Edits",
    "May 2021 Edits", "June 2021 Edits", "JULY 2021 EDITS", "AUGUST EDITS 2021",
    "September 2021 EDITS", "October 2021 Edits", "November 2021 Edits", "December 2021 Edits"
  ],
  "2020 VIDEO POOL EDITS": [
    "FEB 2020 EDITS", "MARCH 2020 EDITS", "APRIL 2020 EDITS", "MAY 2020 EDITS",
    "JUNE 2020 EDITS", "JULY 2020 EDITS", "August 2020 Edits", "SEPTEMBER 2020 EDITS",
    "Octomber 2020 Edits", "November 2020 Edits", "December 2020 EDITS"
  ],
  "Genres": [
    "REGGAE VIDEOS", "Arbantone & Gengetone (Low Hype)", "Arbantone & Gengetone (Hype)",
    "Kenya Love Songs (Hype)", "Kenya Love Songs (Low Hype)", "Locals", "Rnb 2000", "Rnb 2010",
    "Rnb 90", "3 Step Amapiano", "South Africa Amapiano", "Reggae Covers", "Afro Beats (TBT)",
    "Mugithi Covers (Kikuyu)", "Taarabu", "Afro Amapiano", "Mugithi (Kikuyu)", "soul",
    "East Africa TBT (Low Hype)", "East Africa TBT (Hype)", "Urban Pop (Low Hype)", "EDMs",
    "Urban Pop (Hype)", "Urban Pop", "Gospel (Urban)", "Drill Rhumba", "RNB (Low Hype)",
    "Dancehall (Low Hype)", "Bongo (TZ) (Hype)", "UG Music", "Dancehall (Hype)", "RNB (Hype)",
    "Ragga (Low Hype)", "Afro Beats (Naija) (Hype)", "Ragga (Hype)", "Hip Hop",
    "BassHall Dancehall", "Kikuyu Gospel (Kigoco)", "Rhumba (Zilizopendwa)",
    "Bongo (TZ) (Low Hype)", "REGGAE HYPE", "254 Pop Sound", "CRUNK", "ROOTS HYPE",
    "Reggae Gospel Tunes", "90s hits", "Luo Hits", "Luo Music Update", "Tanzania Amapiano",
    "Lingalla Hits", "Bongo Flava (TBT) (TZ) Hype", "Bongo Flava (TBT) (TZ)Low Hype",
    "Kenyan Amapiano", "Urban Amapiano", "dombolo"
  ],
  "Remix & Mashups Hub": [
    "Redrums Video Remixes",
    "DaPhonk (Audio) Remixes",
    "Made In Kenya (DJ Dandana Refixes)",
    "Afro Beats (Audio) Remixes",
    "Reggaetone (Audio) Remixes",
    "Audio Redrums",
    "REMIXAH",
    "DANCEHALL REFIX",
    "Khester Redrums Remixes",
    "R&B Remixes",
    "Amapiano Redrum Remixes",
    "HYPE EDITS",
    "Club Edits",
    "Dancehall Remixes",
    "Amapiano",
    "Afro House",
    "Reggae Fussion"
  ],
  "Riddim Videos": [
    "WYFL Riddim", "Love Echoes Riddim", "Recovery Riddim"
  ],
  "Riddimz F'": [
    "OVER PROOF RIDDIM (PT. 2) - JA-PRODS", "back it up", "BIG DOG RIDDIM - BOARDHOUSE",
    "SIGNATURE BOUNCE RIDDIM - SOUNIQUE", "(97) Riva Stone Riddim(Dj Frass Records)",
    "SOULMATERIDDIM - DUNWELL", "[101]BRIXTON B OUNCE RIDDIM", "Tomatoe Riddim [2012]",
    "Tear Drops Riddim - Cashflow Records Studio", "AFTER SUMMER RIDDIM - G3 MUZIK",
    "BAD ACID RIDDIM - DI GENIUS", "After Summer Riddim (G3 Muzik) 2011",
    "BROKEN HEARTS RIDDIM - DON CORLEON", "Acapella", "01 BIRD'S EYE RIDDIM [MAY 2011]",
    "[www.dancehallzone.net] - SUMMETIME RIDDIM", "KUSH & HENNY RIDDIM - (FULL) - HOT COFFEE MUSIC",
    "112 -Limbo Riddim", "THE RETURN RIDDIM [FULL PROMO] - JUKE BOXX PRODUCTIONS",
    "AFRICAN ROBOT RIDDIM - UNKNOWN PEOPLE RECORDS", "Champions League Riddim  - Madd Spider Productions",
    "SEX ON DI BEACH RIDDIM - SEANIZZLE", "LIFE BLESSINGS RIDDIM - OUTDEH REC", "(100)Smudge Riddim",
    "unruly", "LIFE LESSON RIDDIM - J-ROD RECORDS", "Major & Minor Riddim CD (2010)",
    "SCHOOL FEE RIDDIM - SUBKONSHUS", "OFF THE BENCH RIDDIM [FULL PROMO] - FIRE LINKS PRODUCTION",
    "All i do is win riddim", "EXIT+21+RIDDIM+-+DZ", "085 - Better Life - Cashflow Production [Full]",
    "06 SPITFIRE RIDDIM", "!!4TAP RIDDIM", "(100) Riot Squad Riddim-MASSIVE B PRODUCTION",
    "[www.dancehallzone.net] - BOSS RIDDIM", "MEMORY LANE RIDDIM [FULL PROMO] - LEE MILLA PRODUCTIONS",
    "01 BROKEN HEARTS RIDDIM", "ACKEE SEED RIDDIM", "72 Ghetto Biscuit Riddim - Pearl Haabah Productions",
    "SIMPLICITY RIDDIM [FULL PROMO] - SOUNDBANK MUSIC", "REGGAE PARTY RIDDIM [FULL PROMO] - RUFF TOUCH MOVEMENT - 2016",
    "68 Cold Times Riddim - Ice Drop Records", "76 Hard Times Riddim", "94 Sex Drive Riddim - Pure Music Productions",
    "84 Burn It Down Riddim - Flava Mcgregor", "(109) Stinking Link Riddim-Romeich", "New Day Riddim - Deadline Recordz",
    "[120]MUNGA - MUSIC (MAIN MIX, RADIO & INSTRUMENTAL- JAM2 PRODUCTIONS", "CARIBBEAN PARTY RIDDIM [FULL PROMO] - BIGGY MUSIC - 2014",
    "g whizz - life sweet - dz", "82 RUB A DUB RIDDIM", "88 FOCUS RIDDIM", "74 Ba! Ba! Bum Riddim - Mr G Music",
    "84 Rootsman Riddim", "82 Rebellion Riddim", "84 Rumors Riddim - Soundbank Music",
    "HAMMA BUSINESS RIDDIM [FULL PROMO] - FE2 MUSIC", "BLACKLIGHT RIDDIM [FULL PROMO] - MIXPAK RECORDS",
    "The International Riddim - Real Links Productions", "big up riddim", "83 Tight Rope Riddim - Conquering Lion Records",
    "New Money Riddim -  Fresh Ear Production", "79 Journey Riddim", "81 Gold Rush Riddim - Strike Gold Music",
    "129 bpm Staminizer Riddim", "110 Overproof Riddim Soca Remix Riddim (JA Productions) 2012",
    "88 SUDDEN CHANGE RIDDIM", "WEST PINES RIDDIM [APR 2011]", "[100]CENTRE STAGE RIDDIM",
    "80 Liberty riddim", "79 Sunset Romantic Reggae - Flava Mcgregor Records", "83 CRYBABY RIDDIM",
    "85 Voyage Riddim", "85 NATIVE RIDDIM - ZEE SQUAD RECORDS", "125 bpm Sexy Bitch Riddim (July 2011)(Priceless Records)",
    "84 Guidance & Protection Riddim - Larger Than Life Records", "85 MIXED FEELINGS RIDDIM (FULL PROMO) - DASECA PRODUCTIONS",
    "88 Front Room Riddim - 3 In 1 Records", "85 Nylon Riddim", "84 Meditation riddim",
    "83 Punching Bag Riddim - Down To Earth Records", "75 Kingston 16 Riddim - Honest Music",
    "OBSESSION RIDDIM [PROMO] - ANJU BLAXX _ UIM RECORDS", "88 POETRY RIDDIM [BONUS TRACKS]",
    "VA-Duss_Riddim-(Promo_CD)-2010-YVP_INT", "76 KINGSTON 13 RIDDIM - RANCH ENT", "80 Contagious Riddim - Troyton Music",
    "82 Mission Of Love Riddim - Nap Musiq Productions", "120 BPM Smash Riddim", "WASHINGTON DC RIDDIM",
    "TILT OVA RIDDIM [FULL PROMO] - FULL CHAARGE RECORDS", "85 FUSS CUSS RIDDIM", "85 Seasons Riddim",
    "89 CARDIAC KEYS RIDDIM [FULL PROMO] - ZJ CHROME-CR2O3 RECORDS", "85 Better Life Riddim - Cashflow Production",
    "Selfie Riddim - Cr203 Records", "Wul Dem Riddim - Yellow Moon Records", "78 Every Tongue Shall Riddim - Penthouse Records",
    "83 The Best One Drop Reggae Vol. 1 - FM Records", "[100]G SHOCK RIDDIM - [www.dancehallzone.net]",
    "MOVIN FEVA", "Wahjang Riddim - Fryktion Muzik", "Smudge Riddim (2011)", "TRINI MEDAL RIDDIM  - JAH WAYNE RECORDZ",
    "NO APOLOGY RIDDIM [FULL PROMO] - GAFJAM RECORDS - 2016", "moving feva-101", "Whine and Kotch Riddim 2013",
    "97 THINK TWICE RIDDIM CD (NOVEMBER, 2011)(WARRIORS MUSICK PRODUCTIONS)", "84 PURSUE RIDDIM - CREATIVE NOIZE(3)",
    "No Woman No Cry Riddim", "[146]SPOOK RIDDIM - BLACK SHADOW RECORDS", "120 bpm BEATING STICK RIDDIM - MARKUS RECORDS",
    "88 Kingdom Riddim", "[85]City Life", "82 Longtime_Riddim-(Promo_CD)-2010-YVP_INT",
    "WARM KINGSTON RIDDIM [FULL PROMO] - SIZE 8 RECORDS - 2019", "Rifle Behavior Riddim",
    "Afro Comb Riddim - Jazzwad Records", "105 BPM Trailer Reloaded Riddim CD (2010)",
    "85 Kuff Again Riddim - Tiger Shark Records", "83 Black Shed Riddim", "lotus flower riddim",
    "INTENSITY RIDDIM-103", "86 Struggle Riddim - Weedy G Soundforce", "92 Brick Mansion Riddim - Live MB Music",
    "TWEETY BIRD RIDDIM [FULL PROMO] - RVSSIAN _ HEAD CONCUSSION RECORDS - 2014", "CROWD RESPONSE RIDDIM - DON CORLEON",
    "12 to 12", "9.58 Riddim (July 2012) Penthouse", "2ND CHANCES RIDDIM", "[92]Bubble Gum Riddim-2011",
    "(108) Tekk On Riddim-SUBKONSHUS & D&H", "83 Reggae Rock Riddim - Turf Music Entertainment",
    "124 bpm Party Rock Riddim", "80 Everyday Riddim (Promo CD) 2009", "VA_-_Focus_Riddim-Promo-2009",
    "87 Pearl Riddim 2012", "Brighter Days Riddim", "86 Reggae Fest Riddim - DJ Frass Records",
    "Carbon Copy Riddim - Platta Recordings", "84 Eternity Riddim", "84 Column Riddim - Dawg House Productions",
    "85 Scriptures Riddim - Don Corleon", "Money Mix riddim - Good Good Production", "02 SILKY SMOOTH RIDDIM",
    "96 COUNTRY RUN RIDDIM - KRITIKAL", "73 Red Redemption Riddim - Hungry Lion Records",
    "124 bpm MENKE RIDDIM - FREEZE PROD", "TOP STORY RIDDIM [FULL PROMO] - NOTNICE RECORDS",
    "mad collabo hits", "LOST ANGEL RIDDIM", "85 BROKEN HEARTS RIDDIM - DON CORLEON",
    "REGGAE PICKNEY RIDDIM [FULL PROMO] - TWELVE 9 RECORDS _ LOUD CITY",
    "VA-Word_A_Prayer_Riddim-Promo_CDR-2010-RIDDIM_iNT", "VA-Soca Pack 2017 Vol. 1",
    "124 bpm SUMMER RAVE RIDDIM ", "79 SWEET RIDDIM-NO DOUBT RECORDS", "86 Antique Riddim",
    "80 MOVING RIDDIM [FULL PROMO] - DI GENIUS RECORDS", "84 Ghetto Rock Riddim - TJ Records",
    "85 Big Stage Riddim", "one day riddim", "Knockings Riddim (2011) - Daseca Productions",
    "Qaulity Time Riddim", "77 Full Attention riddim", "TOUCH SCREEN RIDDIM", "[88]Automatic Riddim",
    "[107]BAD ACID RHYTHM CD (JULY, 2011) (BIG SHIP PRODUCTIONS)", "86 ITAL_JOCKEY_RIDDIM-SANKOFA_RECORDS-21ST",
    "87 COOL OUT RIDDIM - GOOD GOOD", "WINNINGS RIDDIM - DI GENIUS!!!!!!!!!!!!!!!",
    "Punjabi Riddim [V.1] - UIM Records", "125 BPM Masterpiece Riddim", "RIOT SQUAD RIDDIM -100",
    "73 King Selassie Throne Riddim - Jammy's", "VIRGIN RIDDIM - (www.dancheallzone.net)",
    "81 One 2 One Riddim", "] - SUMMER SCHEME RIDDIM", "125 bpm Zadaga Riddim - Ancient Records",
    "[86]ANTIQUE RIDDIM", "83 Ice Cold Riddim - Loud City _ J Wonder", "BEACH FRONT RDM-87",
    "85 Island Roots Riddim - Don Corleon Records", "Reggae Fest Riddim - DJ Frass Records",
    "80 Watermelon riddim", "80 Devil's Angel Riddim", "125 bpm Applause Riddim",
    "74 Hypnotize Riddim - Kemar Flava McGregor", "SUDDEN CHANGE RIDDIM", "Busy_Signal-Reggae_Music_Again-",
    "Loyal Riddim - Ashad Records", "Nympho Riddim - Full Chaarge Records", "81 NO. 1 riddim",
    "86 THE MESSAGE - DON CORLEON", "FEEL GOOD RIDDIM [FULL PROMO] DOWNSOUND RECORDS",
    "78 Meddi Riddim - Da Works Enternational", "(100) QMIA Rdm", "128 bpm 3 Star Riddim - R.H.T Entertainment",
    "85 Old Friends Compilation - Island Yard Productions", "85 CITY LIFE RIDDIM CD (2010)",
    "ENVIABLE RIDDIM [FULL PROMO] - STUDIO VIBES ENTERTAINMENT - 2019", "CALIENTE RIDDIM [FULL PROMO] - DUNWELL PRODUCTIONS",
    "84 World Love Riddim - Lionheart Productions", "KATANA RIDDIM", "Jouvert Riddim (UIM Records)  February 2012",
    "86 ColdHeart Riddim", "[101]CLUB HOPPIN RIDDIM", "82 Country Bus Riddim - Chimney Records",
    "VA_-_12_Furlong_Riddim-Promo-2009-MGZ", "87 SWEET SOUNDS RIDDIM", "SANTIAGO RIDDIM [FULL PROMO] - SOUNDBANK MUSIC",
    "chapter_a_day_riddim", "ANIMAL INSTINCT", "78  Man down riddim", "79 Knock Knock Riddim",
    "BUBBL GUM", "85 SUNSHINE RIDDIM-SUPAHYPE UPT RECORDS!!!!!!", "SEASON CHANGE RIDDIM [FULL PROMO] - BERTA RECORDS",
    "Love & Emotions Riddim - Brixton Music Group", "90 Heart & Soul Riddim", "(100)Worldwide Riddim",
    "BRIXTON BOUCE RIDDIM - JRK PRODUCTIONS", "bam bam riddim", "85 Scriptures Riddim (Don Corleon)",
    "[100]WORLDWIDE RIDDIM - FRESH EAR PROD", "85 Miracle Riddim", "90 Hard Drugs Riddim", "Dancehall EFx Riddim",
    "Farr Out Riddim - DownSound Records", "85 Suriname Riddim - MV Music", "CRAZY GLUE RIDDIM [FULL PROMO] - DJ FRASS RECORDS",
    "HUMBUG RIDDIM [FULL PROMO] - ZJ CHROME _ CR203 RECORDS", "85 El Toro Riddim - Cell Block Studio Records",
    "Gyal Time Riddim - Trobak E.M.G", "Cardiac Strings Riddim", "71 Coach Riddim", "PURSUE RIDDIM-84",
    "82 Freedom Shines Riddim (2012) - Truckback Records", "05 Braveheart Riddim", "ping riddim",
    "93 Progressive Love - Heavy Beat Records", "94 Bread And Butter Riddim - Sam Diggy Music",
    "90 Reggae Jamming Pt.1 - Zeph Records", "90 Beach Riddim - Inspired Music", "24 GOD PEOPLE RIDDIM",
    "[120]Brit Jam Riddim Reloaded", "Chuck Norris Riddim - Superlynks & Renegade Productions",
    "87 Red Gold & Green Riddim", "75 Peace and Love Riddim", "90 INTRANSIT RIDDIM VOL 2 - NOTICE PRODUCTIONS",
    "75 Hungry Dayz Riddim - Larger Than Life Records", "Uptown Riddim 2010 (Combination Studio Production) 6 tracks",
    "80 Pagans Riddim", "89 Legends of Soul Riddim - Crawba Productions", "Sax On Da Beach Riddim - Keepleft Records",
    "THE STORY RIDDIM [FULL PROMO] - KING HEARTBEAT STUDIO", "Single Packs", "SET IT OFF RIDDIM -",
    "84 I Feel Good Riddim  [2k9]", "VA-Selfie_Riddim-(Promo_CDS)-(More)-2014-YVP_INT",
    "Success & Strive Riddim - Fresh Ear Productions", "83 Humble riddim", "88 SILVER_PLATE_RIDDIM-JUKE_BOXX-21ST",
    "[106]ARMAGIDDION RIDDIM", "120 BPM Applause Riddim", "Sewage Breath Riddim", "84 Good Love Riddim - Lockecity Music Group",
    "Jouvert", "81 Communication Riddim", "Go fi her Riddim", "Stocktown Riddim - Mike Yangstar Records & Nuh Linga Sweden",
    "126 bpm Premium Riddim [2010]", "89 CARDIAC STRINGS RIDDIM", "[95]YUNG RIDDIM - [www.dancehallzone.net]",
    "77 Throw me Herb Riddim", "86 Affection Riddim", "VA-Ital_Stew_Rididm-(Promo_CD)-2010-YVP_INT", "79 My Baby Riddim",
    "82 Reggae Rage Riddim - World Hits Records", "89 Fresh Groove Riddim - Berta Records", "(115)Party Shott Riddim",
    "08 WATERMELON RIDDIM [APR 2011]", "COLD HEART RIDDIM", "89 Cardiac Strings Riddim - CR203 Zj Chrome",
    "West Pines Riddim CD (April, 2011)", "Jupiter riddim", "86 Columbian Drop Riddim",
    "68 Babylon Horns Riddim - Basix Riddim Selection", "Brixton Rock Riddim - Brixton Music Group",
    "79 What to Do Riddim - Royal Order Music", "V6 RIDDIM - ZJ CHROME", "82 Long Time riddim",
    "Bad & Sexy Riddim - Birchill Records", "87 Relationships_Riddim-(FuLL)-(Radio_Ready)-(Fresh_AirArif_Coop",
    "120 BPM Kopa Riddim", "85 Love Quest Riddim - Kheil Stone Music", "85 GOOD OVA EVIL RIDDIM CD (2010)",
    "72 Heaven Bless Riddim - Ranch Entertainment", "90 CARDIAC KEYS RIDDIM - ZJ CHROME-CR2O3 RECORDS",
    "85 MONTE CARLO RIDDIM [MAY 2011]", "Tin Mackarel riddim-Maximum Soundbwoy Killers",
    "88 Corner Shop Riddim - 21st Hapilos", "83 Roots Reggae Revivalist - Tads Records",
    "76 Fallen_Soldiers_Riddim-Promo-2008-HLC_INT", "87 Tropical Escape Riddim - Chimney",
    "83 Kool Breeze Riddim - Stingray Records", "83 MILITANCY RIDDIM - OVERSTAND ENTERTAINMENT",
    "78 Tough Times Riddim - Hungry Lion Records", "87 COOL OUT RIDDIM 2012 FEB", "84 Brighter Days Riddim - Silly Walks",
    "75 Superior Riddim", "VOODOO RIDDIM", "68 Conscious Energy Riddim - Elite Ent Society Music",
    "86 Ital_Jockey_Riddim-Promo_CDR-RIDDIM_iNT", "[89]Cardiac Strings Rhythm CD (September, 2011) (CR203 Records)",
    "CANDY SHACK RIDDIM [FULL PROMO] - STADIC & JONNY BLAZE", "82 9.58_riddim [Penthouse records]",
    "86 Netzah Riddim", "92 Poison Arrow Riddim - Dj Wilscot™", "Chemistry_Riddim_(PROMO_CD)-2008-R2R",
    "Love Tri Angle Riddim - UIM Records", "89 Grass Root Riddim - Free Willy Music", "SOCA SINGLES PACK - FEBRUARY 2014",
    "85 Solommon Riddim", "120 bpm BOILING POINT RIDDIM", "87 Relationship riddim",
    "88 FOCUS RIDDIM [FULL PROMO] - VIKINGS PRODUCTION", "YOUNG MONEY RIDDIM - GOOD GOOD",
    "[85]Big stage riddim", "85 Secrets Riddim-Don Corleon", "BAM BAM THE SEQUEL RIDDIM", "Stop sign",
    "[87]Cool Out Riddim - Good Good", "FLOUR RIDDIM",
    "85 Bitter Sweet Riddim 2012 (Creative Noize) By Howie RWC [www.reggaeworldcrew.net]",
    "81 Chi Chi Bud Riddim (Full Promo)", "82 Rumours riddim", "67 7 Series Riddim - Dynasty Records",
    "82 9.58 RIDDIM", "90 FAIRGROUND RIDDIM", "89 Real Life Story Riddim - Mighty Crown _ Life Style Records",
    "(101) Stop Sign Riddim", "Better Days Riddim - Oneness Records", "[89]CARDIAC BASS RIDDIM CD (2010)",
    "82 I-NINE RIDDIM-2008", "Blueberry Haze Riddim [Maximum Sound] 2016@ReggaeUp",
    "82 Sea Of Love Riddim Vol. 2 - Skinny Bwoy Records", "GO-GO_CLUB_RIDDIM-RUSSIAN-21ST",
    "75 Kangol Riddim - Gold Dynasty Music", "TWINKLE BOSS RIDDIM [FULL PROMO] - TP PRODUCTIONS",
    "VA-Summer_Scheme_Riddim-Promo-2011-V_Q", "[92]TNS Riddim Pt. 2 - ZJ Chrome", "84 Touch Riddim",
    "Island Roots Riddim - Don Corleon Records", "KOLO KOLO", "84 Guardian Angel",
    "86 Feelings_Riddim-Promo_-2010-DeejayDulmerse@yahoo.com", "(100) Master's Blend Riddim(JA Productions)",
    "(92) TNS Riddim-ZJ CHROME", "88 LIVE IN LOVE RIDDIM", "78 Dis Ya Time Riddim", "69 Jamrock Riddim EP - 12 To 12 Muzik",
    "85 Street Of Gold Riddim CD (May, 2013)(Penthouse Records)", "AfroSoca Riddim - Optimus ProductionsTT",
    "[85]Better Life Riddim", "84 -PURSUE RIDDIM [APR 2011]", "Live In Love Riddim - TJ Records",
    "(104) Jouvert Riddim(UIM RECORDS)", "Material Riddim (Dutty Rock Entertainment) November 2011",
    "19 CLUB HOPPIN RIDDIM", "77 Festival Jam Riddim - Adriatic Sound",
    "120 bpm Hypejenik Rhythm CD (November, 2011)(Peela Productions)", "88 GRACE & GRATITUDE RIDDIM",
    "90 Emotions Riddim", "Skelenton Riddim", "80 Free Riddim", "8806 Riddim Pt.1 - Stampede Music",
    "Snap Back Riddim", "[www.dancehallzone.net] - THINK TWICE RIDDIM", "Automatic Riddim",
    "103 Love Jump Riddim - Upsetta Records & Flow Productions", "83 One Time Love Riddim - One Time Studio",
    "92 PERFECT KEY RIDDIM [FULL PROMO] - DZL RECORDS", "Wibble wobble riddim", "123 bpm Baheba Riddim",
    "124 bpm STRESS FREE RIDDIM CD (RAW)", "03 quality time riddim", "85  Supreme Riddim_",
    "VA-Feelings_Riddim-Promo_CDR-2010-RIDDIM_iNT", "[130]CURRANT RIDDIM CD (MARCH, 2011)",
    "85 Mixed Feelings Riddim - Daseca", "88 AUTOMATIC RIDDIM FULL", "83 Utopia Riddim - Trainline Records",
    "[93]COOK HENNESSY RIDDIM", "71 AUGUST TOWN RIDDIM", "84 Touch Dem Riddim (Promo CD)",
    "120 bpm Championship Riddim 2010", "XOXO Riddim - Cr203 Records", "NEW MONEY",
    "Tropical Escape Riddim CD (December, 2012)(Chimney Records)", "SALT SHAKER RIDDIM [FULL PROMO] - FULL CHAARGE RECORDS",
    "02 CITY STREETZ RIDDIM", "Rox box rdm-100", "85 Monte Carlo riddim", "The employer riddim [cashflow]",
    "76 Dance Drop Riddim - FM Records", "82 Rose Apple Riddim (More) CD", "89 Cardiac Bass Riddim",
    "85 SWEET CORN RIDDIM - PURE MUSIC PRODUCTIONS", "crown love extended",
    "85 On The Corner Riddim - Ghetto Youths International", "courty bus riddim", "Destination Riddim",
    "84 Again Riddim - Total Satsfaction", "TIMES SQUARE RIDDIM", "Late Summer Riddim - Adde Productions",
    "BUS STOP RIDDIM(MASTERED)-FEB.2011", "LOVE SALUTE RIDDIM", "VA-Soca Pack 2017 Vol. 3", "69 GANG_WAR_RIDDIM",
    "73 Steamaz Riddim - Biggy Music", "VA-Soca Pack 2017 Vol. 4", "120 bpm Bed Squeek Riddim CD (April, 2011) [Edit]",
    "87 GHETTO LIFESTYLE RIDDIM - ROMEICH RECORDS", "83 Going Home Riddim - Larger Than Life",
    "70 August_Town_riddim", "LOVESICK RIDDIM [FULL PROMO] - VIKINGS PRODUCTION",
    "84 Infatuation Riddim - Full Chaarge Records", "25 SWEET WATA RIDDIM - JUKE BOXX PRODUCTIONS",
    "PIPE WATA RIDDIM - TOUCH GOLD RECORDS", "130 bpm OPEN SEASON RIDDIM [FULL PROMO] - JAMMIN' RECORDS",
    "Chi chi Bud Riddim Full Promo", "CARDIAC BASS RIDDIM CD", "[101]CLEARANCE RIDDIM",
    "[84]Drop Leaf Riddim CD (2005)", "100 -SMOKIN' RIDDIM", "87 Reggaemiles Riddim - Jugglerz Records",
    "75 Righteous Trod Riddim - Black Street Music", "78 Jah Message - Tads Records", "78 Breaking Up Riddim",
    "Steel Strings Riddim (Chimney Records) September 2011", "Day Dream Riddim - Soca 2017",
    "85 HeartSrings Riddim", "SO BAD RHYTHM CD (OCTOBER, 2011)(YOUNG VIBEZ PRODUCTIONS)",
    "79 911 RIDDIM [FULL PROMO] - SUPERSONIC SOUND", "17 MATRIMONY RIDDIM",
    "85 FEMININE RIDDIM-DON_CORLEON-21st", "75 Holiday Inn Riddim (2009)",
    "80 - Selection Riddim CD (April, 2013)(First Name Music)", "120 bpm Sim Card Riddim - Homebase & Precision",
    "76 REBELLION RIDDIM", "89 Halfway Tree Riddim", "Destination Riddim - Endorsements Regime",
    "Tripple bounce riddim", "85 Live From Kingston Riddim - Stainless Music",
    "90 IN TRANSIT RIDDIM - NOTICE PRODUCTIONS", "77 SWEET_RIDDIM-NO_DOUBT",
    "[100]MAD WORLD RIDDDIM [FULL PROMO] - DI GENIUS RECORDS - 2013",
    "83 FAITHFUL RHYTHM CD (DECEMBER, 2011)(CASHFLOW RECORDS)",
    "COOL OUT RIDDIM [FULL PROMO] - GOODGOOD PRODUCTIONS", "Diamonds & Golds riddim", "Dem Bow Riddim -98",
    "128 bpm PROBLEM RIDDIM 2 (MARCH, 2011)", "93 GO FI HER RIDDIM - PENTHOUSE - DZ",
    "Coca-Cola Riddim CD (January, 2012) (Rama Studios Inc)", "84 DIAMONDS AND GOLD RIDDIM [FULL PROMO] - DJ FRASS RECORDS",
    "66 INNA RUB A DUB STYLE RIDDIM - JOHN JOHN", "(103)Take Over Riddim", "VA-Soca Pack 2017 Vol. 2",
    "ZION TRAIN 2014 - LIVITY RECORDS", "Stand Tall Riddim [www.wegotitfirst.com]", "BRIT JAM RELOAD",
    "Going Home Riddim - Larger Than Life", "78 Real Life Riddim (Full)", "86 Miss Independent Riddim Reggae Remix",
    "87 CHANGES RIDDIM [don corleon]", "84 Rebelious Riddim - Soundbank  Music-2009-JW876",
    "80 Heavenly Riddim", "Big Stage Riddim (2010)", "86 COLD HEART RIDDIM [FULL PROMO] - BIGYARD MUSIC",
    "First Move Riddim - Hardball Entertainment", "70 Ruff Jam Riddim - Jam Promotion", "88 MATCHBOX RIDDIM",
    "81 TIMES SQUARE RIDDIM", "74 Sweet Aroma Riddim - Kalibandulu & Princevibe", "125 BPM Diwali Riddim",
    "Red Gold Green Riddim [Dub Tone Music] 2016 @ReggaeUp", "[98]BUS STOP RIDDIM",
    "74 HONEY POT RIDDIM [CD PROMO] - 2013 SILLY WALKS DISCOTHEQUE", "BULLET TRAIN RIDDIM CD (2010)",
    "RAVE RIDDIM [FULL PROMO] - SILVER BIRDS RECORDS", "[88]Corner Shop Riddim - 21st Hapilos",
    "[81]COMMUNICATION RIDDIM CD (2011)", "79 She's royal riddim", "84 Stand Strong Riddim - Millbeatz Entertainment",
    "86 ANTIQUE RIDDIM - DON CORLEON", "90 BLESSING RIDDIM - ROACH!!!!!!",
    "VA-Wallabeez_Riddim_(Full)-Promo_CDR-2010-RIDDIM_iNT", "[99]Coolie Gal Riddim - UIM Records",
    "87 O.M.G RIDDIM CD (FEBRUARY, 2011)", "43 WINNERS RIDDIM", "DEMBOW RIDDIM KIRAGZ DATA",
    "87 DREAM RIDDIM - BABY G", "85 Feels So Good Riddim (ROMEICH RECORDS) (2010)",
    "127 BPM Ready and Willing Riddim", "80 ZION TRAIN RIDDIM - LIVITY RECORDS",
    "86 BPM REGGAE FEST RIDDIM [FULL PROMO] - DJ FRASS RECORDS", "85 Good Love Riddim  [2k9]",
    "83 GOING HOME RIDDIM RELOAD [FULL PROMO] - LARGER THAN LIFE RECORDS - 2014",
    "7th Heaven Riddim - DJ Frass Records", "88 POETRY RIDDIM [FULL PROMO] - ALL CONNECT RECORDS",
    "MOSKATO RIDDIM [FULL PROMO] - BIRCHILL RECORDS", "81 83 Riddim", "CLUB LIFE RIDDM [FULL PROMO] - LEE MILLA PRODUCTION",
    "Jambe-An Riddim - Techniques Records", "120 BPM Coolie Dance Riddim", "121 bpm MAS FUEGO RIDDIM - KEEP LEFT RECORDS",
    "01 ALIVE RIDDIM", "Nana Gel Riddim - Mango Tree Entertainment", "73 Chant down babylon riddim",
    "78 Joe Frazier Riddim  Digital-B", "86 Soul Roots Riddim - Big Link Production", "GUALA GUALA RIDDIM [2007]",
    "(105) Gaza World Riddim", "85 Broken Hearts Riddim (Don Corleon) June 2011", "INDISCRETION RIDDIM",
    "21 TRUE FEELING RIDDIM", "85 Beach House Riddim - Jamlink", "High Class Riddim  - Cornelius Records",
    "MOTIVATION RIDDIM [PROMO] - SEANIZZLE RECORDS", "THE PLEASURE RIDDIM",
    "SPOT CHECK RIDDIM CD (JULY, 2011)(WUNDAH PRODUCTIONS)",
    "79 Paul Elliot & Friends Reggae Paradise - Hypocrit Riddim - Stronger Productions", "Ebola Riddim UIM Records",
    "60 Coco Remix", "84 Drop Leaf Riddim", "87 GHETTO LIFESTYLE RIDDIM CD (FEBRUARY, 2012)(ROMEICH RECORDS)",
    "120 bpm MICE TRAP RIDDIM (SEPTEMBER 2011) - PRB PRODUCTION", "Bubbla_Riddim-(Promo_CD)-2014-YVP_INT",
    "129 bpm purge_riddim 2007", "88 Live In Love Riddim - TJ Records", "brain storm riddim", "Island roots riddim",
    "89 Paper loving Riddim", "High Rave Riddim - Full Chaarge Records", "120 bpm Overtime Riddim [Soca Remixes]",
    "93 Riddim - Black Roots Music", "[100]Area 51 Riddim - Head Concussion",
    "Brixton Swerve Riddim - Brixton Music Group", "91 INDISCRETION RIDDIM",
    "84 All Natural Riddim - Ghetto Youths International", "BLESSINGS RIDDIM [FULL PROMO] - JA PRODUCTIONS",
    "85 Yandlink Riddim", "(98)Drink & Party Riddim", "81 Questions Riddim", "89 Serve & Protect Riddim -  Penthouse Music",
    "[106]CONTRA RIDDIM", "[81]83 RIDDIM", "80 Raining Bass Riddim (February 2012) Fams House Music",
    "86 Dancehall Sings Riddim [Roots Edition] - Cr203 Records", "81 Drop It Riddim - FM Records",
    "VA-Everyday_Riddim-WEB-2009-RIDDIM_iNT", "90 DIGITAL LOVE RIDDIM (NOVEMBER 2012) NOTICE PRODUCTIONS",
    "GHETTO ROCK RIDDIM [FULL PROMO] - TJ RECORDS", "WORLD FETE RIDDIM [FULL PROMO] - TJ RECORDS",
    "82 Lava Ground Riddim", "80 Fight This Feeling Riddim - Ranch Entertainment",
    "88 Four Seasons Riddim - Fireman Crew Production", "[158]MYSTERY RIDDIM - YARD VYBZ ENTERTAINMENT",
    "86 Dancehall Sings Riddim [Love Edition] - Cr203 Records", "80 HORIZON RIDDIM - RANDY RICH PROD - [SPRB]",
    "(100) Riot Squad Riddim", "89 St. Ann'z Riddim - Unity Yawd Family",
    "71 I'm Still In Love With You Riddim CD (2002)(Fi Wi Music)", "92 Natural Juice Riddim - Kingstone Records",
    "87 Lazy Song Riddim", "84 Feel good riddim", "83 NEW CHAPTER RIDDIM [CD PROMO] - 2009 BIG SHIP",
    "Breakaway Riddim (February 2016) Chimney Records", "18 STEADY FLOW RIDDIM", "86 FEELINGS RIDDIM CD (2010)",
    "[90]chill spot riddim", "WIBBLE WABBLE RIDDIM CD (2008)", "73 The Rock Steady Riddim - Smart Kid Records",
    "86 Reggae World Riddim - Master Kat Productions", "AURORA SKIES RIDDIM - SOUNIQUE", "Major & Minor Riddim",
    "84 Pretenders Riddim - FME Recordings", "(97) Riva Stone Riddim(Dj Frass Records) 2012",
    "80 Rockers Railway Riddim - Forever Music", "77 The Empire Riddim - Riddim Wise", "CHANGES RIDDIM",
    "QMIA RIDDIM [PROMO] - QMIA PRODUCTIONS", "11 ELEVEN RIDDIM [FULL PROMO] - MARKUS RECORDS",
    "78 Crystal Woman Riddim", "Roof Top Riddim-104"
  ]
};
